spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/yang-zhuwei/CGB2104-4.git
          search-paths: springcloud01/config
  rabbitmq:
    host: 192.168.126.140
    port: 5672
    username: admin
    password: admin
server:
  port: 6001
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh