spring:
  application:
    name: order-service
  cloud:
    config:
      override-none: true
server:
  port: 8201
eureka:
  client:
    service-url:
      # /eureka 路径是客户端通信的路径
      defaultZone: http://eureka1:2001/eureka
  rabbitmq:
    host: 192.168.126.140
    port: 5672
    username: admin
    password: admin
